#!/usr/bin/env bash
# script that Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
# what about this command
# sudo sed -i 's/\blisten 80\b/listen 80 default_server/' /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# sudo ufw allow 'Nginx HTTP'
service nginx start