#!/usr/bin/env bash
# script that Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
# what about below command to connect port 80
# sudo sed -i 's/\blisten 80\b/listen 80 default_server/' /etc/nginx/sites-available/default
# sudo ufw allow 'Nginx HTTP'
echo "Hello World!" |sudo tee /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo nginx -t
sudo service nginx restart
