#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server.
sudo apt -y update
sudo apt -y install haproxy

sudo sed -i "11i ENABLED=1" /etc/default/haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 100.26.167.191:80 check
    server web-02 54.173.241.59:80 check
EOT

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart