#!/usr/bin/env bash
# nstall and configure HAproxy on lb-01 server.
apt-get -y update
apt-get -y install haproxy

sudo sed -i "9i ENABLED=1" /etc/default/haproxy

echo '
frontend itri.tech
	bind *:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 427525-web-01 100.26.167.191 check
	server 427525-web-02 54.173.241.59 check
' >> /etc/haproxy/haproxy.cfg

service haproxy restart