#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_root_password>"
    exit 1
fi

mysql_root_password=$1
backup_dir="."
date_format=$(date +"%d-%m-%Y")
dump_file="backup.sql"
archive_name="${date_format}.tar.gz"

# Create MySQL dump
mysqldump -u root -p"${mysql_root_password}" --all-databases > "${backup_dir}/${dump_file}"

# Compress the dump file into a tar.gz archive
tar -czvf "${backup_dir}/${archive_name}" -C "${backup_dir}" "${dump_file}"

echo "${dump_file}"