#!/usr/bin/env bash
# Bash script that creates the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'; exit" SIGTERM
trap "echo 'Y U no love me?!'; exit" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "rm /var/run/myscript.pid; exit" SIGTERM

while true
do
	echo "To infinity and beyond"
done
