#!/usr/bin/env bash
# Bash script that displays the content of the file
while IFS=':' read -r username password uid gid info home shell; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
