#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but Hi the 9th
counter=0

while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi

	((counter++))
done
