#!/usr/bin/env bash
# Script that accepts one argument and
# run the whoami command under the user passed as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

username=$1

# Run whoami command under the specified user
sudo -u "$username" whoami
